spring:
  #rabbitmq  for auto reflesh config
  rabbitmq:
    host: 192.168.23.147
    port: 5672
    username: guest
    password: guest
    virtual-host: /

#打开info,health等断点，所以需要添加management.endpoints.web.exposure.include=*配置，其他的不变
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${server.port}

feign:
  httpclient:
    enabled: false
    # 关闭SSL证书校验(默认：开启校验-false)，适用于httpclient和okhttpclient
    disable-ssl-validation: true
  okhttp:
    enabled: true
  client:
    config:
      # 默认配置，启动Ribbon时失效（即启用了服务注册发现机制时）
      default:
        connectTimeout: 3000
        readTimeout: 3000
  # 开启熔断
  hystrix:
    enabled: false

### 请求处理的超时时间
ribbon:
  # 等待请求响应的超时时间. 单位：ms
  ReadTimeout: 5000
  # 连接超时时间. 单位：ms
  ConnectTimeout: 1000
  # 是否对所有请求进行失败重试, 设置为 false, 让feign只针对Get请求进行重试.
  OkToRetryOnAllOperations: false
  # Max number of retries on the same server (excluding the first try)
  MaxAutoRetries: 3
  # Max number of next servers to retry (excluding the first server)
  MaxAutoRetriesNextServer: 0